[
    "Why Nations Fail",
    "The Inner Game of Tennis",
    "The Knowledge",
    "The 48 Laws of Power",
    "Evicted",
    "Cataloging the world",
    '"Surely You\'re Joking, Mr. Feynman"',
    "The Diamond Age",
    "The anatomy of racial inequality",
    "The consolations of philosophy",
    "Essais",
    "Nonviolent Communication",
    "Mandarin Chinese",
    "The Secret of Apollo",
    "The Mastery and Uses of Fire in Antiquity",
    "Gödel, Escher, Bach",
    "Algorithms to Live By",
    "Strange tools",
    "The Liberation of Sita",
    "Making Space",
    "Discrimination by design",
    "Hidden Potential",
    "The Ages of Globalization",
    "Scattered",
    "Think on These Things",
    "Race in America",
    "Poverty, by America",
    "Twilight of the Idols and The Antichrist",
    "Comprehension",
    "Schooling in Capitalist America",
    "Inventing Temperature",
    "Chasing the scream",
    "Łańcuchy rytuałów interakcyjnych",
    "Robert A. Heinlein",
    "Industrializing knowledge",
    "The Signal and the Noise",
    "Culture Warlords",
    "Seeing Nature",
    "Scarcity",
    "Codependent No More and Beyond Codependency",
    "The Art of Community",
    "The Culture Map",
    "Siddhartha",
    "Boundaries",
    "The Goldfinch",
    "Toyota production system",
    "The White Man's Burden",
    "Dead aid",
    "The beginning of infinity",
    "Active Inference",
    "How not to hate your husband after kids",
    "Selfish reasons to have more kids",
    "Book of Boundaries",
    "Medieval technology and social change",
    "The lives of a cell",
    "The Four Agreements",
    "Superintelligence",
    "The Inevitable",
    "The evolution of useful things",
    "Black hole focus",
    "Out of control",
    "Good Inside",
    "Working Backwards",
    "The Dispossessed",
    "The Fountainhead",
    "Hood Feminism",
    "The Shallows",
    "Genesis of Technoscientific Revolutions",
    "In the Light of What We Know",
    "Adult children of emotionally immature parents",
    "The 4 disciplines of execution",
    "The divide",
    "Bronze Age Mindset",
    "Atlas Shrugged",
    "Getting to yes",
    "Immune",
    "Japan's Imperial Underworlds",
    "Made to stick",
    "Why Fish Don't Exist",
    "The Tyranny of Merit",
    "On Aristotle",
    "Dick Gregory's political primer",
    "Range",
    "How to Change Your Mind",
    "Ghost Work",
    "Digital_Humanities",
    "Why We Sleep",
    "World brain",
    "Good faith collaboration",
    "The matrix",
    "Library",
    "Too much to know",
    "The Coddling of the American Mind",
    "Bowling Alone",
    "The Psychology of Money",
    "In Defense of Food",
    "The Wizard and the Prophet",
    "Decolonizing wealth",
    "Lessons from the Titans",
    "Thinking, fast and slow",
    "Spiel",
    "The Cold Start Problem",
    "The Body Keeps the Score",
    "Sex at Dawn",
    "Sex and reason",
    "Dubliners",
    "Killing the black body",
    "Are We Smart Enough to Know How Smart Animals Are?",
    "Trust and Reciprocity",
    "Fordlandia",
    "The Righteous Mind",
    "The lost books of the Odyssey",
    "Stand on Zanzibar",
    "Skunk Works : a personal memoir of my years at Lockheed",
    "Thinking in systems",
    "The order of evils",
    "The 7 Habits of Highly Effective People",
    "Predictably Irrational",
    "The Last Man Who Knew Everything",
    "Charlotte's Web",
    "Attached",
    "Maybe You Should Talk to Someone",
    "Autobiography",
    "The Missing Piece Meets the Big O",
    "Doing Good Better",
    "Common Sense",
    "The Master Switch",
    "The Wave",
    "The Giving Tree",
    "Compilers, principles, techniques, and tools",
    "Of Mice and Men",
    "The Art of War: Text and Commentary",
    "Introduction to the Theory of Computation",
    "Harry Potter and the Goblet of Fire",
    "Downsiders",
    "Artificial intelligence",
    "Het Achterhuis",
    "Green Eggs and Ham",
    "Harry Potter and the Half-Blood Prince",
    "The Catcher in the Rye",
    "Im Westen nichts Neues",
    "Novels (Cannery Row / Of Mice and Men)",
    "The Three-Body Problem",
    "Matilda",
    "Downsiders",
    "Voices from the Paterson Silk Mills (Voices of America)",
    "Ready Player One",
    "Introduction to the theory of computation",
    "Risk up front",
    "A short history of nearly everything",
    "Drawdown",
    "Musical acoustics",
    "Operating System Concepts",
    "Network security",
    "Founders at work",
    "Introduction to linear algebra",
    "Introduction to linear algebra",
    "Understanding Symbolic Logic",
    "Cornered",
    "The prince, and selected discourses",
    "Le Comte de Monte Cristo",
    "On Tyranny",
    "The Art of War",
    "Many Waters (Time Quintet #4)",
    "Harry Potter and the Methods of Rationality",
    "Which side are you on?",
    "Φαῖδρος",
    "Who Owns the Future?",
    "Reinventing Organizations",
    "The 22 immutable laws of marketing",
    "The better angels of our nature",
    "Debt",
    "Influence",
    "Lord of Flies",
    "Moral mazes",
    "Understanding Power",
    "Harry Potter and the Order of the Phoenix",
    "The Prince",
    "Harry Potter and the Philosopher's Stone",
    "Glut",
    "How to Win Friends and Influence People",
    "Zen and the Art of Motorcycle Maintenance",
    "The authoritative Calvin and Hobbes",
    "The Giver",
    "Sam Walton",
    "The Legacy",
    "The now habit",
    "The Lone Drow",
    "The Checklist Manifesto",
    "A Swiftly Tilting Planet (Time Quintet #3)",
    "The Hyperlinked Society",
    "William Golding's Lord of the flies",
    "Jumanji",
    "Hatchet",
    "Principles",
    "Animal Farm",
    "Harry Potter and the Prisoner of Azkaban",
    "Streams of Silver",
    "The Demon Apostle",
    "The Demon Spirit",
    "The Highwayman",
    "Assata",
    "High Output Management",
    "The Crystal Shard",
    "The fellowship of the ring",
    "Exile",
    "Animalia",
]
